site_name: Programming 102
pages:
- [index.md, Home]
- [shell.md, Introduction to Linux Shell]
- [git.md, Introduction to Git]
- [python_intro.md, Introduction to Python]
- [python_datatypes.md, Data Types]
- [python_collections.md, Collection Data Types]
- [python_control.md,Control Structures]
- [python_functions.md,Functions]
- [assign.md, Assignments]
- [reminders.md, Reminders]
theme: readthedocs
